# Parsing the datasets

### Importing libraries

In [346]:
# Numpy
import numpy as np
from numpy import concatenate, array
from numpy.random import randn
# Decimal precision value to display in the matrix
np.set_printoptions(precision=5, suppress=True)

# Scipy
import scipy
import scipy.stats as stats

# Matplotlib
import matplotlib.pyplot as pyplot
import matplotlib.cm as cm
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
%matplotlib inline
#mpl.rc('figure', figsize=(10, 8))

# DBscan from sklearn
from sklearn import cluster, datasets
from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import StandardScaler

# Pandas experiments
import pandas as pd
from pandas import Series, DataFrame, Panel

# Misc
import time
import datetime as dt
import math
import random
print 'All libraries loaded.'

All libraries loaded.

## Plot function definitions

In [347]:
def plot_pdf(data, title):
    data.sort()
    pdf = stats.norm.pdf(data, np.mean(data), np.std(data))
    pyplot.plot(data, pdf, '-o', linewidth=3)
    pyplot.grid()
    pyplot.title(title)
    pyplot.show()

# Make dataframes from data

In [134]:
# Make dataframes from data

# eGFR data
egfr_df = pd.read_csv('~/code/independent/datasets/cdr_gfr_derived.csv', parse_dates=['resultdata'])
egfr_df.drop('gfr', axis=1, inplace=True)
egfr_df.columns = ['pid', 'timestamp', 'gender', 'birthyear', 'age', 'gfr']

# Findings data
findings_df = pd.read_csv('~/code/independent/datasets/cdr_finding.csv', parse_dates=['finddate'], usecols=['idperson', 'finddate', 'valuename', 'findvalnum'])
findings_df = findings_df[['idperson', 'finddate', 'valuename', 'findvalnum']]
findings_df.columns = ['pid', 'timestamp', 'testname', 'testval']

# Lab reports data
lab_df = pd.read_csv('~/code/independent/datasets/cdr_lab_result.csv', parse_dates=['resultdate'], usecols=['idperson', 'resultdate', 'valuename', 'resultvaluenum'])
lab_df = lab_df[['idperson', 'resultdate', 'valuename', 'resultvaluenum']]
lab_df.columns = ['pid', 'timestamp', 'testname', 'testval']
# Make all lab tests values uppercase
lab_df.testname = map(lambda x: x.upper(), lab_df.testname)

In [135]:
# Normalize dates (to remove the time part of it)
egfr_df.timestamp = egfr_df.timestamp.map(pd.datetools.normalize_date)
findings_df.timestamp = findings_df.timestamp.map(pd.datetools.normalize_date)
lab_df.timestamp = lab_df.timestamp.map(pd.datetools.normalize_date)

In [136]:
# NaN values
total_rowcount = len(lab_df.testval.values)
nan_rowcount = len([x for x in lab_df.testval.values if math.isnan(x)])
print '\n',(str(nan_rowcount*100/total_rowcount)+ "% of the values are NaN")

# Drop NaN rows
# lab_df.dropna(inplace=True)

1% of the values are NaN

## Make tiny versions of the datasets

In [137]:
howmany = 500000

egfr_df = egfr_df[:howmany]
lab_df = lab_df[:howmany]
findings_df = findings_df[:howmany]

## Make a multi-index/hierarchical index 
#### The index will be a combination of the PID (person ID) and timestamp

In [140]:
# Set the index as a combination of the person ID and timestamp
egfr_df.set_index(['pid', 'timestamp'], inplace=True)
findings_df.set_index(['pid', 'timestamp'], inplace=True)
lab_df.set_index(['pid', 'timestamp'], inplace=True)

## Get list of all patients for whom we have eGFR data

In [340]:
list_of_patients = list(set(egfr_df.index.get_level_values('pid').values))
print '\nFound', len(list_of_patients), 'unique patients'

Found 63215 unique patients

## Get small sample of patients

In [339]:
# Get just 5 patients
# list_of_patients = random.sample(list_of_patients, 5)

# list_of_patients = [8555317, 8555928, 8565179]

ValueError: sample larger than population

## Make the new dataframe (empty)

In [343]:
# Column names will be a combination of all the lab test names and finding names
unique_findings = set(findings_df.testname.values)
unique_labtests = set(lab_df.testname.values)
print '\nFindings:', list(unique_findings)
print 'Lab tests:', list(unique_labtests)
final_col_names = np.append(list(unique_findings), list(unique_labtests))

Findings: ['FND_BPS', 'FND_BPD']
Lab tests: ['LR_AST', 'LR_MICROCR', 'LR_HDL', 'LR_TRIG', 'LR_A1C', 'LR_CR', 'LR_PTH', 'LR_GLUCNONFAST', 'LR_LDL', 'LR_GFR', 'LR_VITD 25', 'LR_ALT', 'LR_PHOS', 'LR_GFR_AFRAMER']

In [366]:
# Row locations in the eGFR dataframe of patients
# locations_of_patients = []
# for patient in list_of_patients:
#     get_loc_result = egfr_df.index.get_loc(patient)
#     locations_of_patients += [i for i,v in enumerate(get_loc_result) if v == True]

# combined_df = DataFrame(egfr_df.iloc[locations_of_patients])
combined_df = pd.DataFrame(egfr_df)

# Add the new columns
for newcol in final_col_names:
    combined_df[newcol] = np.nan

## Fill values into the new dataframe<br>based on joins on the other dataframes

In [ ]:
def fill_data(source_df, patient_id):
    
    ############### Could optimize
    locations_of_patients = []
    if str(patient_id) in source_df.index:
        
#         get_loc_result = source_df.index.get_loc(str(patient_id))
#         locations_of_patients += [i for i,v in enumerate(get_loc_result) if v == True]
#         this_patients_data = source_df.iloc[locations_of_patients]
        this_patients_data = source_df.loc[str(patient_id)]

        # We only need data for the dates that exist in the combined DF already 
        # (the ones that have eGFR readings)
        for timestamp in combined_df.loc[patient_id].index:
            if timestamp in this_patients_data.index.get_level_values('timestamp'):
                this_patient = this_patients_data.loc[timestamp]

                # Set the value in the DF for this test
                # Check if there's multiple values for the same timestamp
                if type(this_patient) == pd.core.frame.DataFrame:
                    for i in range(this_patient.testname.size):
                        combined_df.loc[(patient_id, timestamp), this_patient.testname[i]] = this_patient.testval[i]
                else:
                    combined_df.loc[(patient_id, timestamp), this_patient.testname] = this_patient.testval

fill_count = 0
for patient_id in list_of_patients:
    if fill_count % 500 == 0:
        print 'Data fill for', fill_count, 'patients complete.'

    # Check if the findings df has data about this patient
    fill_data(findings_df, patient_id)

    # Check if the lab-tests df has data about this patient
    fill_data(lab_df, patient_id)
    
    fill_count += 1

combined_df

Data fill for 0 patients complete.
Data fill for 500 patients complete.
Data fill for 1000 patients complete.
Data fill for 1500 patients complete.
Data fill for 2000 patients complete.
Data fill for 2500 patients complete.
Data fill for 3000 patients complete.
Data fill for 3500 patients complete.
Data fill for 4000 patients complete.
Data fill for 4500 patients complete.
Data fill for 5000 patients complete.
Data fill for 5500 patients complete.
Data fill for 6000 patients complete.
Data fill for 6500 patients complete.
Data fill for 7000 patients complete.
Data fill for 7500 patients complete.
Data fill for 8000 patients complete.
Data fill for 8500 patients complete.
Data fill for 9000 patients complete.
Data fill for 9500 patients complete.
Data fill for

Int64Index([8545332, 8545332, 8545332, 8545332, 8545332, 8545332, 8545333,
            8545333, 8545333, 8545336,
            ...
            9581807, 9581807, 9581807, 9581807, 9581807, 9581807, 9581807,
            9581811, 9581815, 9581824],
           dtype='int64', name=u'pid', length=466108)
True
           testname  testval
timestamp
2011-05-17  FND_BPS      132
2011-09-19  FND_BPS      124
testname    FND_BPS
testval         124
Name: 2011-09-19 00:00:00, dtype: object

In [365]:
# How many values are NaNs
total_rowcount = len(combined_df.FND_BPS.values)
nan_rowcount = len([x for x in combined_df.FND_BPS.values if math.isnan(x)])
print '\n',(str(nan_rowcount*100/total_rowcount)+ "% of the values are NaN")
combined_df.size

98% of the values are NaN

9322160

In [364]:
combined_df

                   gender  birthyear  age        gfr  FND_BPS  FND_BPD  \
pid     timestamp
8545332 2006-08-11      F       1924   90  46.662023      NaN      NaN
        2006-11-02      F       1924   90  46.662023      NaN      NaN
        2007-06-05      F       1924   90  52.087166      NaN      NaN
        2010-02-09      F       1924   90  49.235491      NaN      NaN
        2010-08-17      F       1924   90  45.235376      NaN      NaN
        2011-04-13      F       1924   90  52.694794      NaN      NaN
8545333 2007-05-31      F       1941   73  48.687812      NaN      NaN
        2010-06-10      F       1941   73  52.525870      NaN      NaN
        2010-06-10      F       1941   73  52.525870      NaN      NaN
8545336 2010-11-18      F       1928   86  43.858349      NaN      NaN
        2011-09-01      F       1928   86  46.605380      NaN      NaN
8545337 2010-10-29      F       1924   90  49.782219      NaN      NaN
8545338 2007-10-11      F       1948   66  44.946862      NaN      NaN
8545339 2010-05-24      F       1946   68  40.733527      NaN      NaN
        2010-05-24      F       1946   68  40.733527      NaN      NaN
8545340 2007-04-19      F       1926   88  52.325329      NaN      NaN
        2007-10-01      F       1926   88  46.875381      NaN      NaN
        2007-10-09      F       1926   88  52.325329      NaN      NaN
        2008-12-18      F       1926   88  39.354252      NaN      NaN
8545341 2006-12-06      F       1943   71  48.963150      NaN      NaN
        2007-03-26      F       1943   71  44.285479      NaN      NaN
8545342 2007-02-20      F       1931   83  47.435332      NaN      NaN
        2007-07-19      F       1931   83  52.950382      NaN      NaN
8545344 2007-11-26      F       1954   60  45.824960      NaN      NaN
8545345 2009-06-25      F       1950   64  48.476906      NaN      NaN
8545346 2009-01-15      F       1950   64  48.976734      NaN      NaN
8545347 2010-10-29      F       1955   59  46.882111      NaN      NaN
        2010-10-29      F       1955   59   0.459047      NaN      NaN
8545348 2006-08-10      F       1941   73  54.348481      NaN      NaN
        2009-05-04      F       1941   73  46.253234      NaN      NaN
...                   ...        ...  ...        ...      ...      ...
9581790 2011-05-06      M       1925   89  45.096620      NaN      NaN
9581791 2011-08-29      M       1928   86  52.808746      NaN      NaN
9581793 2011-09-02      M       1935   79  47.982772      NaN      NaN
        2011-09-02      M       1935   79  47.982772      NaN      NaN
        2011-11-08      M       1935   79  38.878560      NaN      NaN
        2012-02-15      M       1935   79  36.088184      NaN      NaN
        2012-03-01      M       1935   79  41.249352      NaN      NaN
9581799 2011-06-24      M       1926   88  33.297182      NaN      NaN
9581800 2011-01-06      M       1936   78  58.294589      NaN      NaN
        2011-03-08      M       1936   78  53.865890      NaN      NaN
        2011-08-08      M       1936   78  51.667671      NaN      NaN
        2011-10-18      M       1936   78  55.270443      NaN      NaN
        2012-01-24      M       1936   78  53.412414      NaN      NaN
9581801 2011-03-30      M       1942   72  54.748289      NaN      NaN
        2011-07-20      M       1942   72  48.153399      NaN      NaN
        2011-08-16      M       1942   72  46.731386      NaN      NaN
        2011-11-19      M       1942   72  48.153399      NaN      NaN
9581803 2011-03-16      M       1936   78  61.642951      NaN      NaN
        2011-11-01      M       1936   78  57.252864      NaN      NaN
9581807 2010-10-29      M       1944   70  32.988795      NaN      NaN
        2010-11-10      M       1944   70  27.916462      NaN      NaN
        2010-11-23      M       1944   70  30.641986      NaN      NaN
        2011-03-08      M       1944   70  19.591036      NaN      NaN
        2011-03-30      M       1944   70  32.633267      NaN      NaN
        2011-04-18      M       1944   70  27.655770      NaN      NaN
        2011-06-07      M       1944   70  26.066265      NaN      NaN
        2011-08-05      M       1944   70  25.836778      NaN      NaN
9581811 2011-04-15      M       1935   79  62.677758      NaN      NaN
9581815 2012-03-01      M       1989   25   0.480012      NaN      NaN
9581824 2012-03-01      M       1972   42   0.369152      NaN      NaN

                    LR_AST  LR_MICROCR  LR_HDL  LR_TRIG  LR_A1C  LR_CR  \
pid     timestamp
8545332 2006-08-11     NaN         NaN     NaN      NaN     NaN    NaN
        2006-11-02     NaN         NaN     NaN      NaN     NaN    NaN
        2007-06-05     NaN         NaN     NaN      NaN     NaN    NaN
        2010-02-09     NaN         NaN     NaN      NaN     NaN    NaN
        2010-08-17     NaN         NaN     NaN      NaN     NaN    NaN
        2011-04-13     NaN         NaN     NaN      NaN     NaN    NaN
8545333 2007-05-31     NaN         NaN     NaN      NaN     NaN    NaN
        2010-06-10     NaN         NaN     NaN      NaN     NaN    NaN
        2010-06-10     NaN         NaN     NaN      NaN     NaN    NaN
8545336 2010-11-18     NaN         NaN     NaN      NaN     NaN    NaN
        2011-09-01     NaN         NaN     NaN      NaN     NaN    NaN
8545337 2010-10-29     NaN         NaN     NaN      NaN     NaN    NaN
8545338 2007-10-11     NaN         NaN     NaN      NaN     NaN    NaN
8545339 2010-05-24     NaN         NaN     NaN      NaN     NaN    NaN
        2010-05-24     NaN         NaN     NaN      NaN     NaN    NaN
8545340 2007-04-19     NaN         NaN     NaN      NaN     NaN    NaN
        2007-10-01     NaN         NaN     NaN      NaN     NaN    NaN
        2007-10-09     NaN         NaN     NaN      NaN     NaN    NaN
        2008-12-18     NaN         NaN     NaN      NaN     NaN    NaN
8545341 2006-12-06     NaN         NaN     NaN      NaN     NaN    NaN
        2007-03-26     NaN         NaN     NaN      NaN     NaN    NaN
8545342 2007-02-20     NaN         NaN     NaN      NaN     NaN    NaN
        2007-07-19     NaN         NaN     NaN      NaN     NaN    NaN
8545344 2007-11-26     NaN         NaN     NaN      NaN     NaN    NaN
8545345 2009-06-25     NaN         NaN     NaN      NaN     NaN    NaN
8545346 2009-01-15     NaN         NaN     NaN      NaN     NaN    NaN
8545347 2010-10-29     NaN         NaN     NaN      NaN     NaN    NaN
        2010-10-29     NaN         NaN     NaN      NaN     NaN    NaN
8545348 2006-08-10     NaN         NaN     NaN      NaN     NaN    NaN
        2009-05-04     NaN         NaN     NaN      NaN     NaN    NaN
...                    ...         ...     ...      ...     ...    ...
9581790 2011-05-06     NaN         NaN     NaN      NaN     NaN    NaN
9581791 2011-08-29     NaN         NaN     NaN      NaN     NaN    NaN
9581793 2011-09-02     NaN         NaN     NaN      NaN     NaN    NaN
        2011-09-02     NaN         NaN     NaN      NaN     NaN    NaN
        2011-11-08     NaN         NaN     NaN      NaN     NaN    NaN
        2012-02-15     NaN         NaN     NaN      NaN     NaN    NaN
        2012-03-01     NaN         NaN     NaN      NaN     NaN    NaN
9581799 2011-06-24     NaN         NaN     NaN      NaN     NaN    NaN
9581800 2011-01-06     NaN         NaN     NaN      NaN     NaN    NaN
        2011-03-08     NaN         NaN     NaN      NaN     NaN    NaN
        2011-08-08     NaN         NaN     NaN      NaN     NaN    NaN
        2011-10-18     NaN         NaN     NaN      NaN     NaN    NaN
        2012-01-24     NaN         NaN     NaN      NaN     NaN    NaN
9581801 2011-03-30     NaN         NaN     NaN      NaN     NaN    NaN
        2011-07-20     NaN         NaN     NaN      NaN     NaN    NaN
        2011-08-16     NaN         NaN     NaN      NaN     NaN    NaN
        2011-11-19     NaN         NaN     NaN      NaN     NaN    NaN
9581803 2011-03-16     NaN         NaN     NaN      NaN     NaN    NaN
        2011-11-01     NaN         NaN     NaN      NaN     NaN    NaN
9581807 2010-10-29     NaN         NaN     NaN      NaN     NaN    NaN
        2010-11-10     NaN         NaN     NaN      NaN     NaN    NaN
        2010-11-23     NaN         NaN     NaN      NaN     NaN    NaN
        2011-03-08     NaN         NaN     NaN      NaN     NaN    NaN
        2011-03-30     NaN         NaN     NaN      NaN     NaN    NaN
        2011-04-18     NaN         NaN     NaN      NaN     NaN    NaN
        2011-06-07     NaN         NaN     NaN      NaN     NaN    NaN
        2011-08-05     NaN         NaN     NaN      NaN     NaN    NaN
9581811 2011-04-15     NaN         NaN     NaN      NaN     NaN    NaN
9581815 2012-03-01     NaN         NaN     NaN      NaN     NaN    NaN
9581824 2012-03-01     NaN         NaN     NaN      NaN     NaN    NaN

                    LR_PTH  LR_GLUCNONFAST  LR_LDL  LR_GFR  LR_VITD 25  \
pid     timestamp
8545332 2006-08-11     NaN             NaN     NaN     NaN         NaN
        2006-11-02     NaN             NaN     NaN     NaN         NaN
        2007-06-05     NaN             NaN     NaN     NaN         NaN
        2010-02-09     NaN             NaN     NaN     NaN         NaN
        2010-08-17     NaN             NaN     NaN     NaN         NaN
        2011-04-13     NaN             NaN     NaN     NaN         NaN
8545333 2007-05-31     NaN             NaN     NaN     NaN         NaN
        2010-06-10     NaN             NaN     NaN     NaN         NaN
        2010-06-10     NaN             NaN     NaN     NaN         NaN
8545336 2010-11-18     NaN             NaN     NaN     NaN         NaN
        2011-09-01     NaN             NaN     NaN     NaN         NaN
8545337 2010-10-29     NaN             NaN     NaN     NaN         NaN
8545338 2007-10-11     NaN             NaN     NaN     NaN         NaN
8545339 2010-05-24     NaN             NaN     NaN     NaN         NaN
        2010-05-24     NaN             NaN     NaN     NaN         NaN
8545340 2007-04-19     NaN             NaN     NaN     NaN         NaN
        2007-10-01     NaN             NaN     NaN     NaN         NaN
        2007-10-09     NaN             NaN     NaN     NaN         NaN
        2008-12-18     NaN             NaN     NaN     NaN         NaN
8545341 2006-12-06     NaN             NaN     NaN     NaN         NaN
        2007-03-26     NaN             NaN     NaN     NaN         NaN
8545342 2007-02-20     NaN             NaN     NaN     NaN         NaN
        2007-07-19     NaN             NaN     NaN     NaN         NaN
8545344 2007-11-26     NaN             NaN     NaN     NaN         NaN
8545345 2009-06-25     NaN             NaN     NaN     NaN         NaN
8545346 2009-01-15     NaN             NaN     NaN     NaN         NaN
8545347 2010-10-29     NaN             NaN     NaN     NaN         NaN
        2010-10-29     NaN             NaN     NaN     NaN         NaN
8545348 2006-08-10     NaN             NaN     NaN     NaN         NaN
        2009-05-04     NaN             NaN     NaN     NaN         NaN
...                    ...             ...     ...     ...         ...
9581790 2011-05-06     NaN             NaN     NaN     NaN         NaN
9581791 2011-08-29     NaN             NaN     NaN     NaN         NaN
9581793 2011-09-02     NaN             NaN     NaN     NaN         NaN
        2011-09-02     NaN             NaN     NaN     NaN         NaN
        2011-11-08     NaN             NaN     NaN     NaN         NaN
        2012-02-15     NaN             NaN     NaN     NaN         NaN
        2012-03-01     NaN             NaN     NaN     NaN         NaN
9581799 2011-06-24     NaN             NaN     NaN     NaN         NaN
9581800 2011-01-06     NaN             NaN     NaN     NaN         NaN
        2011-03-08     NaN             NaN     NaN     NaN         NaN
        2011-08-08     NaN             NaN     NaN     NaN         NaN
        2011-10-18     NaN             NaN     NaN     NaN         NaN
        2012-01-24     NaN             NaN     NaN     NaN         NaN
9581801 2011-03-30     NaN             NaN     NaN     NaN         NaN
        2011-07-20     NaN             NaN     NaN     NaN         NaN
        2011-08-16     NaN             NaN     NaN     NaN         NaN
        2011-11-19     NaN             NaN     NaN     NaN         NaN
9581803 2011-03-16     NaN             NaN     NaN     NaN         NaN
        2011-11-01     NaN             NaN     NaN     NaN         NaN
9581807 2010-10-29     NaN             NaN     NaN     NaN         NaN
        2010-11-10     NaN             NaN     NaN     NaN         NaN
        2010-11-23     NaN             NaN     NaN     NaN         NaN
        2011-03-08     NaN             NaN     NaN     NaN         NaN
        2011-03-30     NaN             NaN     NaN     NaN         NaN
        2011-04-18     NaN             NaN     NaN     NaN         NaN
        2011-06-07     NaN             NaN     NaN     NaN         NaN
        2011-08-05     NaN             NaN     NaN     NaN         NaN
9581811 2011-04-15     NaN             NaN     NaN     NaN         NaN
9581815 2012-03-01     NaN             NaN     NaN     NaN         NaN
9581824 2012-03-01     NaN             NaN     NaN     NaN         NaN

                    LR_ALT  LR_PHOS  LR_GFR_AFRAMER
pid     timestamp
8545332 2006-08-11     NaN      NaN             NaN
        2006-11-02     NaN      NaN             NaN
        2007-06-05     NaN      NaN             NaN
        2010-02-09     NaN      NaN             NaN
        2010-08-17     NaN      NaN             NaN
        2011-04-13     NaN      NaN             NaN
8545333 2007-05-31     NaN      NaN             NaN
        2010-06-10     NaN      NaN             NaN
        2010-06-10     NaN      NaN             NaN
8545336 2010-11-18     NaN      NaN             NaN
        2011-09-01     NaN      NaN             NaN
8545337 2010-10-29     NaN      NaN             NaN
8545338 2007-10-11     NaN      NaN             NaN
8545339 2010-05-24     NaN      NaN             NaN
        2010-05-24     NaN      NaN             NaN
8545340 2007-04-19     NaN      NaN             NaN
        2007-10-01     NaN      NaN             NaN
        2007-10-09     NaN      NaN             NaN
        2008-12-18     NaN      NaN             NaN
8545341 2006-12-06     NaN      NaN             NaN
        2007-03-26     NaN      NaN             NaN
8545342 2007-02-20     NaN      NaN             NaN
        2007-07-19     NaN      NaN             NaN
8545344 2007-11-26     NaN      NaN             NaN
8545345 2009-06-25     NaN      NaN             NaN
8545346 2009-01-15     NaN      NaN             NaN
8545347 2010-10-29     NaN      NaN             NaN
        2010-10-29     NaN      NaN             NaN
8545348 2006-08-10     NaN      NaN             NaN
        2009-05-04     NaN      NaN             NaN
...                    ...      ...             ...
9581790 2011-05-06     NaN      NaN             NaN
9581791 2011-08-29     NaN      NaN             NaN
9581793 2011-09-02     NaN      NaN             NaN
        2011-09-02     NaN      NaN             NaN
        2011-11-08     NaN      NaN             NaN
        2012-02-15     NaN      NaN             NaN
        2012-03-01     NaN      NaN             NaN
9581799 2011-06-24     NaN      NaN             NaN
9581800 2011-01-06     NaN      NaN             NaN
        2011-03-08     NaN      NaN             NaN
        2011-08-08     NaN      NaN             NaN
        2011-10-18     NaN      NaN             NaN
        2012-01-24     NaN      NaN             NaN
9581801 2011-03-30     NaN      NaN             NaN
        2011-07-20     NaN      NaN             NaN
        2011-08-16     NaN      NaN             NaN
        2011-11-19     NaN      NaN             NaN
9581803 2011-03-16     NaN      NaN             NaN
        2011-11-01     NaN      NaN             NaN
9581807 2010-10-29     NaN      NaN             NaN
        2010-11-10     NaN      NaN             NaN
        2010-11-23     NaN      NaN             NaN
        2011-03-08     NaN      NaN             NaN
        2011-03-30     NaN      NaN             NaN
        2011-04-18     NaN      NaN             NaN
        2011-06-07     NaN      NaN             NaN
        2011-08-05     NaN      NaN             NaN
9581811 2011-04-15     NaN      NaN             NaN
9581815 2012-03-01     NaN      NaN             NaN
9581824 2012-03-01     NaN      NaN             NaN

[466108 rows x 20 columns]

In [ ]:
# lab_df.loc['8555580', '2010-02-22']

# lab_df.loc['8554722'].loc['2009-02-20']
# lab_df.loc['8554722']

lab_df.iloc[lab_df.index.get_level_values('pid')=='8554722']

# x = lab_df.xs('8555580', level='pid')['2010-02-22']
# x

print lab_df.xs('8555580', level='pid')['2010-02-22']

# lab_df
# lab_df['8554722']['2008-04-07']
# lab_df['2010-02-22']

# .xs('2009-02-20', level='timestamp')
# x.index.searchsorted(stamp)
# x['2008-02-04']